export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const RETRIEVE_ACCOUNTS = 'RETRIEVE_ACCOUNTS';
export const RETRIEVE_ALL_ACCOUNTS = 'RETRIEVE_ALL_ACCOUNTS';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const DELETE_ALL_ACCOUNTS = 'DELETE_ALL_ACCOUNTS';

export const CREATE_PRODUCT_PARAMS = 'CREATE_PRODUCT_PARAMS';
export const RETRIEVE_PRODUCT_PARAMS = 'RETRIEVE_PRODUCT_PARAMS';
export const RETRIEVE_ALL_PRODUCT_PARAMS = 'RETRIEVE_ALL_PRODUCT_PARAMS';
export const UPDATE_PRODUCT_PARAMS = 'UPDATE_PRODUCT_PARAMS';
export const DELETE_PRODUCT_PARAMS = 'DELETE_PRODUCT_PARAMS';
export const DELETE_ALL_PRODUCT_PARAMS = 'DELETE_ALL_PRODUCT_PARAMS';

export const CREATE_PRODUCT_INFOS = 'CREATE_PRODUCT_INFOS';
export const RETRIEVE_PRODUCT_INFOS = 'RETRIEVE_PRODUCT_INFOS';
export const RETRIEVE_ALL_PRODUCT_INFOS = 'RETRIEVE_ALL_PRODUCT_INFOS';
export const UPDATE_PRODUCT_INFOS = 'UPDATE_PRODUCT_INFOS';
export const DELETE_PRODUCT_INFOS = 'DELETE_PRODUCT_INFOS';
export const DELETE_ALL_PRODUCT_INFOS = 'DELETE_ALL_PRODUCT_INFOS';
